Update Gitpod images at docs environment #9734
EddieHubCommunity/BioDrop pull request #10029
Opened 2023-12-26 13:32 UTC by dominic-source

This commit will update images in the Gitpod doc environment.

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-12-26 21:18 UTC, amandamartin-dev commented
Hello! Can you please link the issue this PR will close.

2023-12-26 22:36 UTC, dominic-source commented
#9734 

Here it is.

2023-12-27 10:59 UTC, SaraJaoude commented
> #9734
> 
> Here it is.

Thank you @dominic-source  - in future could you please add this to the section in the Template description called `Fixes Issue`.  This allows for the issue to be closed automatically once the PR is merged, which helps maintainers manage the project.

2023-12-27 12:20 UTC, dominic-source commented
Thanks so much, I apologise for all the delays. I'm new to open source, so I'll correct now on.
Thanks.

2024-01-05 13:19 UTC, dominic-source commented
Hello, I wanted to ask if this pull request has been pulled. Because I notice it still appears here.

2024-01-10 07:00 UTC, ArvindParekh commented
Hi @dominic-source. No it has not been merged yet, the maintainers will do that soon 👍🏻

2024-01-10 13:23 UTC, kumarsonsoff3 requested changes

2024-01-10 13:23 UTC, kumarsonsoff3 commented on data/dominic-source.json
You've created an empty file `data/dominic-source.json` which is not related to this issue. Could you please remove this file [here](https://github.com/dominic-source/BioDrop/delete/main/data/dominic-source.json).

And to create a profile using `json` you can follow [these docs](https://www.biodrop.io/docs/quickstart-json), & create a new PR from another branch.

2024-01-10 13:34 UTC, dominic-source commented
Thanks for the observation
 I have deleted the file, please kindly confirm and provide me feedback.

Thanks & Regards

On Wed, Jan 10, 2024, 2:24 PM Priyanshu kumawat ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On data/dominic-source.json
> <https://github.com/EddieHubCommunity/BioDrop/pull/10029#discussion_r1447380270>
> :
>
> You've created an empty file data/dominic-source.json which is not
> related to this issue. Could you please remove this file here
> <https://github.com/dominic-source/BioDrop/delete/main/data/dominic-source.json>
> .
>
> And to create a profile using json you can follow these docs
> <https://www.biodrop.io/docs/quickstart-json>, & create a new PR from
> another branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/10029#pullrequestreview-1813217691>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQHINNOCQFP2J4JJQ72UZM3YN2I7VAVCNFSM6AAAAABBDJL4P2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJTGIYTONRZGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-10 13:35 UTC, dominic-source commented on data/dominic-source.json
Thanks for the observation. 
I have deleted the file, please kindly confirm and provide me feedback.

Thanks and Regards.

2024-01-10 14:07 UTC, merged