data:Tk-brainCodes
EddieHubCommunity/BioDrop pull request #10038
Opened 2023-12-27 13:11 UTC by Tk-brainCodes

## Changes proposed

<p>Add a new file data/Tk-brainCodes.json which contains my Linkfree profile links</p>

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<p>This PR contains my bio data for Linkfree, in the directory data/Tk-brainCodes .

2023-12-27 13:30 UTC, sital002 requested changes
Your file should be inside data folder instead of ```Tk-brainCodes .json``` it should be ```data/Tk-brainCodes .json````.
Please make the necessary changes to get your profile merged

2023-12-27 13:33 UTC, sital002 commented on Tk-brainCodes.json
> +      "github": "Github",
```suggestion
```
github isnot a valid property 
I will attach a quick guide link here https://www.biodrop.io/docs/quickstart-json

2023-12-27 13:34 UTC, sital002 commented on Tk-brainCodes.json
> +      "portfolio": "Portfolio",
```suggestion
```
portfolio isnot a valid property

2023-12-27 13:34 UTC, sital002 commented on Tk-brainCodes.json
> +      "linkedin": "Linkedin",
```suggestion
```

2023-12-27 13:34 UTC, sital002 commented on Tk-brainCodes.json
> +      "twitter": "Twitter",
```suggestion
```

2024-01-09 16:54 UTC, SaraJaoude commented
We look forward to seeing your Profile on BioDrop, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at t[hese Docs](https://www.biodrop.io/docs/quickstart-json) which will help with the suggested changes the maintainers have proposed. 

Please remember you can also create your Profile using [Forms](https://www.biodrop.io/docs/quickstart-forms).

2024-01-09 16:54 UTC, closed without merging