data:navitha2255
EddieHubCommunity/BioDrop pull request #10072
Opened 2024-01-01 14:44 UTC by navitha2255

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2024-01-01 15:26 UTC, xkrishguptaa requested changes
Hi! You have created an incorrect profile:

1. the json syntax is invalid, you have missed quotes and some places
2. You used eddie's links and avatar, please update with your own
3. The extension for the json has a typo, it should `navitha2255.json`

2024-01-01 18:30 UTC, SaraJaoude commented on data/navitha2255.jsomn
> +  "type":"personsl",
these are no longer necessary:
```suggestion
```

2024-01-01 18:30 UTC, SaraJaoude commented on data/navitha2255.jsomn
> +  "avatar":https://github.com/eddiejaoude2.png",
this is not necessary:
```suggestion
  "bio":"iam a frontend developer",
```

2024-01-01 18:32 UTC, SaraJaoude commented on data/navitha2255.jsomn
> +      "icon":"FaGithubAlt'
closing `"` rather than `'`
```suggestion
      "icon":"FaGithubAlt"
```

2024-01-01 18:35 UTC, SaraJaoude commented on data/navitha2255.jsomn
> +      "url":https://twitter.com/eddiejaoude",
Please replace this with your own twitter account. 

You are also missing a `"` in front of `https `

2024-01-01 18:36 UTC, SaraJaoude requested changes
I have made most of the changes needed for the JSON to pass, but before we can merge your PR as mentioned in another comment please

-  update the Twitter link so that it is your own
- change the file name to have `json` and the end and not `jsomn`

2024-01-02 09:40 UTC, SaraJaoude commented
Please see my comments [here.  ](https://github.com/EddieHubCommunity/BioDrop/pull/10075/files)

If you need help with editing a PR please check out [this documentation](https://www.biodrop.io/docs/how-to-guides/editing-json) and come and chat to us on the EddieHub Discord.

2024-01-16 16:00 UTC, SaraJaoude commented
We look forward to seeing your Profile on BioDrop, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at t[hese Docs](https://www.biodrop.io/docs/quickstart-json) which will help with the suggested changes the maintainers have proposed. 

Please remember you can also create your Profile using [Forms](https://www.biodrop.io/docs/quickstart-forms).

2024-01-16 16:00 UTC, closed without merging