Create temple.json
EddieHubCommunity/BioDrop pull request #10080
Opened 2024-01-02 15:57 UTC by temple69

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2024-01-03 06:43 UTC, sital002 requested changes
Your filename must match your github username instead of ```data/temple.json``` it should be ```data/temple69.json```  
Please make the necessary changes to get your profile merged.

2024-01-04 13:15 UTC, temple69 commented
@sital002 I have made the necessary  changes

2024-01-04 14:56 UTC, kumarsonsoff3 requested changes

2024-01-04 14:56 UTC, kumarsonsoff3 commented on data/temple.json
Please remove `temple.json`, as you've created 2 files with same content.

2024-01-16 16:02 UTC, SaraJaoude commented
We look forward to seeing your Profile on BioDrop, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at t[hese Docs](https://www.biodrop.io/docs/quickstart-json) which will help with the suggested changes the maintainers have proposed. 

Please remember you can also create your Profile using [Forms](https://www.biodrop.io/docs/quickstart-forms).

2024-01-16 16:02 UTC, closed without merging