feat: added middleware.js to protect all pages under admin
EddieHubCommunity/BioDrop pull request #8410
Opened 2023-07-30 16:40 UTC by ashmeetsmonga

## Fixes Issue #8389

## Changes proposed

- Added a new file middleware.js in root which handles protected routes (/admin/*) 
- Removed individual files check

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-30 21:13 UTC, eddiejaoude commented on pages/admin/events.js
> -
The middleware should check for `admin` user, please see the lines below...

2023-07-30 21:17 UTC, eddiejaoude requested changes
Thank you for your contribution 👍 

Please fix...
- the issue for this middleware is to check for admin users on the path `/admin/*` and `/api/admin/*` with the environment variable `serverEnv.ADMIN_USERS`
- for session only check the path to protect is `/account/*` and `/api/account*`
- admin page `profiles` has been forgotten

2023-07-31 06:43 UTC, ashmeetsmonga commented
Nextjs middleware run on Edge runtime, which as far as I have researched, doesn't support env variables. Is there a way to get env variables in middleware?

2023-07-31 06:54 UTC, eddiejaoude commented
> I am facing issue with env variables. Nextjs middleware run on Edge runtime, which as far as I have researched, doesn't support env variables. Is there a way to get env variables in middleware?

here are the official Vercel docs https://vercel.com/changelog/more-flexible-environment-variables-in-edge-functions-and-middleware

2023-07-31 08:40 UTC, ashmeetsmonga commented
Thank you for your patience and answering my queries. I appreciate it. 
I have few doubts: 
I was getting an error when using `serverEnv.ADMIN_USERS` in middleware.js, so I used `process.env.ADMIN_USERS`.
I have not removed individual check for session in account page, will do that after you approve changes.
Took pull from main after pushing changes (my bad), would remove admin check from profile page also after your approval. 
Thanks

2023-07-31 08:47 UTC, eddiejaoude commented
- Did you import for `serverEnv.ADMIN_USERS`? We need to use this to be consistent and also validate the environment variables
- Please remove any commented out code, as this makes it difficult to review and test

2023-09-14 06:39 UTC, ChinmayMhatre commented
@eddiejaoude wanted to push this incase it slipped by. @ashmeetsmonga you can post you question in the discord channel as well so that other members in the community can help.

2023-09-14 06:52 UTC, closed without merging