data/saadali05.json
EddieHubCommunity/BioDrop pull request #8752
Opened 2023-08-24 07:41 UTC by saadali05

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-24 08:13 UTC, sital002 requested changes
Your filename must match your github username and the file must be inside data folder.
Please move the file from saadali.json to data/saadali05.json .

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```
Please add comma

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```

2023-08-24 08:13 UTC, sital002 commented on saadali.json
> +    }
```suggestion
    },
```

2023-08-25 07:48 UTC, SaraJaoude requested changes
Please move your file to the data folder and make sure that your file name matches your GitHub username exactly. Instead of `saadali.json` it should be `data/saadali05.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

2023-08-30 10:18 UTC, merged