data: kush6291.json
EddieHubCommunity/BioDrop pull request #8838
Opened 2023-08-29 09:53 UTC by kush6291

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-29 11:24 UTC, sital002 requested changes

2023-08-29 11:24 UTC, sital002 commented on data/kush6291.json
> +  "displayStatsPublic": true,
```suggestion
```
displayStatsPublic  is no longer required. Please remove it.

2023-08-29 11:24 UTC, sital002 commented on data/kush6291.json
> +        "name": "Follow me on twitter"
```suggestion
        "name": "Follow me on twitter",
```
Please add comma here

2023-08-29 11:24 UTC, sital002 commented on data/kush6291.json
> +        "name": "Follow me on github"
```suggestion
        "name": "Follow me on github",
```
please add comma here

2023-08-29 11:24 UTC, sital002 commented on data/kush6291.json
> +      },
```suggestion
      }
```
The trailing comma is not required.

2023-08-29 11:24 UTC, sital002 commented on data/kush6291.json
> +  "avatar": "https://github.com/kush6291.png"
```suggestion
```
avatar property is no longer is required.

2023-08-30 07:32 UTC, SaraJaoude commented on data/kush6291.json
> +  "bio" "I am a DevOps Engineer",
```suggestion
  "bio": "I am a DevOps Engineer",
```

2023-08-30 07:34 UTC, SaraJaoude approved these changes
Now the corrections to validate the json have been made this looks good and I can merge

2023-08-30 07:35 UTC, merged