Gold star added
EddieHubCommunity/BioDrop pull request #8857
Opened 2023-08-30 00:06 UTC by JakeDamon

## Fixes Issue ##8848

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-08-30 03:29 UTC, sital002 reviewed
This is just a suggestion:
Instead of adding a star we could a crown icon similar to this with gold color.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/d2bd719d-047f-438a-9de7-3caaa72e5523)


Before Changes:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/435e89dc-c6ee-4826-ab8d-cf49c511f5f0)


After Changes:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/e22a36ed-8893-493a-8eda-996001fa2066)
And on more thing if we are displaying the gold star just after the name anyone can add a emoji similar to star that will cause problem instead if it's a premium user then we should have a tooltip that will show a message like Premium badge on hover on the icon.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/0fbcaa12-2802-4683-9772-6abbcd9e9c7b)

Here you could see that if I just add emoji to the name field it will create a problem.

2023-08-30 08:53 UTC, eddiejaoude commented on components/user/UserProfile.js
> +            <ImStarFull color="gold" />
The tests are failing, not sure why they are asking for a title in the icon 🤔 

```
"description": "Ensures each HTML document contains a non-empty <title> element",
```

2023-08-30 12:09 UTC, JakeDamon commented
I will add a modal so when clicked, it will display a Premium Account description. Much like X's verified account blue check.

2023-09-01 08:13 UTC, eddiejaoude requested changes
Thanks for the contribution Jake 👍 

There seems to be many other changes in your pull request, I think it is because you are using the same branch `premium-strip` that you are merging into, so it is difficult to keep it up to date? Can you fix your PR so it only has your changes in it, thanks

2023-09-01 12:25 UTC, JakeDamon commented
Closing to reopen to get latest changes.

2023-09-01 12:25 UTC, closed without merging