fix: Update image in how-to testimonials page (#8814)
EddieHubCommunity/BioDrop pull request #8865
Opened 2023-08-30 11:42 UTC by rahulsiddarth

Update BioDrop testimonial issue image in testimonials-json.mdx

## Fixes Issue

Closes #8814 

## Changes proposed

Update BioDrop testimonial issue image in how-to testimonials page with the new application name (LinkFree -> BioDrop)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

<img width="960" alt="Screenshot 2023-08-30 170925" src="https://github.com/EddieHubCommunity/BioDrop/assets/43289009/6083b09a-2836-47fe-a268-88393006257e">

<img width="960" alt="Screenshot 2023-08-30 170842" src="https://github.com/EddieHubCommunity/BioDrop/assets/43289009/3c904015-5957-42e5-8b91-1e501d404b8a">

## Note to reviewers

2023-09-01 11:49 UTC, eddiejaoude commented on pages/docs/how-to-guides/testimonials-json.mdx
> +![BioDrop testimonial issue]https://github.com/EddieHubCommunity/BioDrop/assets/43289009/15f7d441-1b68-424a-99d5-00fe8bc47537)
This is not valid markdown

2023-09-01 11:49 UTC, eddiejaoude requested changes
Thank you for your contribution. But the issue is to update all images used in the docs

2023-09-01 11:52 UTC, xkrishguptaa commented on pages/docs/how-to-guides/testimonials-json.mdx
> +![BioDrop testimonial issue]https://github.com/EddieHubCommunity/BioDrop/assets/43289009/15f7d441-1b68-424a-99d5-00fe8bc47537)
Like Eddie mentioned, you just have to add this `(`

```suggestion
![BioDrop testimonial issue](https://github.com/EddieHubCommunity/BioDrop/assets/43289009/15f7d441-1b68-424a-99d5-00fe8bc47537)
```

2023-09-06 07:31 UTC, SaraJaoude commented
> Hello Eddie, requesting that this issue be reassigned to someone who has a better screen size. Currently, with my 16:9 screen ratio , I'm unable to capture all the details like how it is present now in the screenshots.

@rahulsiddarth thank you for the work you did and I will unassigned the issue and also as a result close this PR.

2023-09-06 07:31 UTC, closed without merging