data: remove my JSON file
EddieHubCommunity/BioDrop pull request #8910
Opened 2023-09-01 15:56 UTC by Panquesito7

## Changes proposed

- Remove my profile JSON file.
  - From what I understand, profiles are now managed via forms, thus, no longer needing these files.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

None.

2023-09-02 05:49 UTC, kumarsonsoff3 requested changes
Please remove the related files too. 

As discussed on discord, just keep the testimonials files until the bug is resolved! 

https://github.com/EddieHubCommunity/BioDrop/tree/main/data/Panquesito7/events

2023-09-13 11:11 UTC, guibranco approved these changes

2023-09-18 03:20 UTC, kumarsonsoff3 commented
@Panquesito7, just a reminder on this. Please remove the events file related to your profile too as now you're managing your profile via forms. (Link mentioned in the comment above).

2023-10-02 08:44 UTC, SaraJaoude commented
As there is no recent activity from the author to make the changes suggested I am going to close this pull request.

2023-10-02 08:44 UTC, closed without merging