Update linkfree-cli.mdx
EddieHubCommunity/BioDrop pull request #8916
Opened 2023-09-02 07:35 UTC by sanyamx

Changed it to match current name "BioDrop"

## Fixes Issue
closes #8845 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

I would like to know more about if there are any future consideration of changing the CLI name as well so as to create a uniformity in the documents. If yes i would like to update the document more.
Thanks! Please review and let me know if there are any changes required!
Happy Reviewing

2023-09-03 13:23 UTC, sital002 requested changes

2023-09-03 13:23 UTC, sital002 commented on pages/docs/environments/linkfree-cli.mdx
>  ![LinkFree CLI main prompt](https://user-images.githubusercontent.com/51878265/220891756-10861090-e719-4687-b4fb-f7bef2826934.png)
Please change this as well.

2023-09-04 16:47 UTC, Pradumnasaraf requested changes
Hey,

Check this comment: https://github.com/EddieHubCommunity/BioDrop/issues/8845#issuecomment-1705529907

2023-09-05 04:31 UTC, sanyamx commented
> Hey,
> 
> Check this comment before you proceed further: [#8845 (comment)](https://github.com/EddieHubCommunity/BioDrop/issues/8845#issuecomment-1705529907)

Sure! i will just update the name where there is LinkFree to BioDrop, you can do the rest!
I will be more than happy to help if i can contribute to CLI as well, please let me know if i can contribute!

2023-09-05 07:58 UTC, Pradumnasaraf commented
Hey,

Please read the comment https://github.com/EddieHubCommunity/BioDrop/issues/8845#issuecomment-1705529907

> 1st the CLI will get a rename, then the docs will proceed (Hopefully soon). Also, I will be self-assigning this issue to make this change.

Thanks. I am still in the process of renaming. You can look at the project and see the way you can contribute.

2023-09-07 04:57 UTC, closed without merging