feat: add Tags Input feature
EddieHubCommunity/BioDrop pull request #8954
Opened 2023-09-05 09:23 UTC by badrivlog

## Fixes Issue

Closes #8766 
## Changes proposed
* Created a new **`TagsInput`** component for inputting and displaying tags
* Implement a  **`handleKeyUp`** event handler for separate tags, when the **`COMMA`** key presses. If the input field is not empty, tags will be added and displayed as individual elements.
* Implement a **`handleKeyDown`** event handler for the **`BACKSPACE`** key when the input field is focused. Check if the input field is empty and the user presses **`BACKSPACE`**. If the conditions are met, remove the last tag from the state and update the input field to display the removed tag
* Attach an **`onClick`** event handler to each rendered tag element, when a tag is clicked, call a function to remove the clicked tag from the state.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
![TagsInput](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/419c2357-fe15-4d77-a254-0f9a2b9d6a5c)

dark mode:
![tagsInput dark](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/f2fe0b3d-a3cd-4fbf-bb36-ff28f2ee0af5)

2023-09-06 17:53 UTC, badrivlog commented on components/tag/TagsInput.js
> +          remove {tag} tag
These words are not needed by sighted users, they are there to provide more information about what the button does for screen reader users who do not have the extra visual context to help them.

2023-09-06 18:05 UTC, badrivlog commented on components/tag/TagsInput.js
> +        </span>
This icon would be read out in screen readers ("cross mark"). Using `aria-hidden` puts a stop to that

2023-09-13 06:48 UTC, eddiejaoude commented on components/tag/TagsInput.js
> +    if (e.keyCode !== comma) return;
We don't use this code styling anywhere, so I think better to use brackets

```suggestion
    if (e.keyCode !== comma) {
       return;
    }
```

2023-09-13 06:48 UTC, eddiejaoude commented on components/tag/TagsInput.js
> +    if (!newTag) return;
Same here

2023-09-13 06:50 UTC, eddiejaoude commented on pages/account/manage/profile.js
> +    const updatedTags = tags.filter((_, index) => index !== indexOfTagToRemove);
Is `findIndex` needed? I think this can be done with just a `filter`?

2023-09-13 06:51 UTC, eddiejaoude requested changes
Looks good and works great 👍

2023-09-13 07:01 UTC, badrivlog commented
> Looks good and works great 👍 

Thanks for reviewing the PR🎉 I will make changes as you suggested

2023-09-13 07:02 UTC, eddiejaoude commented
Thank you @badrivlog , sorry for being slow in reviewing, I was away at events all last week and weekend, so catching up now

Awesome! Then we can merge 🎉

2023-09-13 18:12 UTC, eddiejaoude approved these changes
Looks good, thank you 👍

2023-09-13 18:14 UTC, merged

2023-09-13 18:14 UTC, xkrishguptaa approved these changes