Add YouTube links to community-resources.json
EddieHubCommunity/BioDrop pull request #9053
Opened 2023-09-13 17:22 UTC by Nenepo

2023-09-13 17:53 UTC, eddiejaoude commented on config/community-resources.json
> +    "name": "Nafisa Faruna",
The name here should be the creator of the resource

```suggestion
    "name": "Kim McMahon",
```

2023-09-13 17:54 UTC, Nenepo commented
Oh alright
I will fix it
On Wed, 13 Sep 2023 at 6:54 PM, Eddie Jaoude ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In config/community-resources.json
> <https://github.com/EddieHubCommunity/BioDrop/pull/9053#discussion_r1324872728>
> :
>
> > @@ -98,5 +98,15 @@
>        "name": "Maximising Your Job Prospects in Tech with BioDrop",
>        "url": "https://loftwah.medium.com/maximising-your-job-prospects-in-tech-with-BioDrop-2fea408301cc"
>      }
> +  },
> +  {
> +    "name": "Nafisa Faruna",
>
> The name here should be the creator of the resource
> ⬇️ Suggested change
>
> -    "name": "Nafisa Faruna",
> +    "name": "Kim McMahon",
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/9053#pullrequestreview-1625120803>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPFC72SDXKFN6SZEJ7H7ALX2HXLZANCNFSM6AAAAAA4WYYHOI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-13 17:55 UTC, eddiejaoude commented on config/community-resources.json
> +    "username": "Nenepo",
This should be the username of the resource author 

```suggestion
    "username": "KimMcMahon",
```

2023-09-13 17:55 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 

I have left 2 small inline comments

2023-09-13 17:56 UTC, Nenepo commented
Thanks for the feedback!

On Wed, 13 Sep 2023 at 6:55 PM, Eddie Jaoude ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for the contribution 👍
>
> I have left 2 small inline comments
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/9053#pullrequestreview-1625126748>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPFC7ZHGFLMT55PG4T5LM3X2HXSTANCNFSM6AAAAAA4WYYHOI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-14 22:18 UTC, eddiejaoude commented
No worries, you can push more commits to your fork branch and GitHub will add it to this open pull request

2023-09-23 20:52 UTC, eddiejaoude commented
@Nenepo do you need help with making these changes?

2023-09-23 20:56 UTC, Nenepo commented
Hyyyyy
Not at the moment, I would have to go back and check it out
I did the push already and sent in an email
I had no idea it did not work
Sorry about that


> @Nenepo <https://github.com/Nenepo> do you need help with making these
> changes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/9053#issuecomment-1732407025>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPFC72C3PJLVKPEN3ZM3ODX35D27ANCNFSM6AAAAAA4WYYHOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-23 23:14 UTC, Nenepo commented
> @Nenepo do you need help with making these changes?

Hyyyyy I realized I didn’t open a pull request
I just opened it

2023-09-24 04:56 UTC, eddiejaoude commented
> No worries, you can push more commits to your fork branch and GitHub will add it to this open pull request

I will close this PR as you have created a new one https://github.com/EddieHubCommunity/BioDrop/pull/9153

2023-09-24 04:56 UTC, closed without merging

2023-09-24 06:43 UTC, Nenepo commented
Thank you,I had to open another branch because I kept pushing and it was
not reflecting on GitHub but I could see the commit on my local server
I got tired of trying to figure it out😫

>
> No worries, you can push more commits to your fork branch and GitHub will
> add it to this open pull request
>
> I will close this PR as you have created a new one #9153
> <https://github.com/EddieHubCommunity/BioDrop/pull/9153>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/9053#issuecomment-1732477416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPFC7ZBZXKLOKWC5YSHDI3X364QBANCNFSM6AAAAAA4WYYHOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>