feat: remove a stat info from landing page
EddieHubCommunity/BioDrop pull request #9079
Opened 2023-09-15 13:24 UTC by rahulsiddarth

Closes #8885 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-09-15 16:08 UTC, rizahmeds commented
@rahulsiddarth Could you please add the screenshots?

2023-09-15 16:58 UTC, accodes21 reviewed
Looks good, thanks for contributing

2023-09-21 06:47 UTC, eddiejaoude commented on components/statistics/BasicCards.js
> -                  )}
This code needs to remain, this component is used in other places in the app

2023-09-21 06:48 UTC, eddiejaoude requested changes
Thank you or your contribution 👍 

I have added inline comments

2023-09-22 06:21 UTC, eddiejaoude commented
> Looks good, thanks for contributing

@accodes21 please do not approve pull requests without reviewing properly, this causes noise and confusing to the contributor and the maintainers

2023-09-22 06:23 UTC, eddiejaoude approved these changes
Looks good, thank you 👍

2023-09-22 06:23 UTC, accodes21 commented
> > Looks good, thanks for contributing
> 
> @accodes21 please do not approve pull requests without reviewing properly, this causes noise and confusing to the contributor and the maintainers

Extremely sorry for causing any confusion, will remember not to make such mistakes again

2023-09-22 06:23 UTC, merged