[Fix] : added warning to manage event page
EddieHubCommunity/BioDrop pull request #9112
Opened 2023-09-20 06:49 UTC by adarshmalviya12

## Fixes Issue

closes #8964

## Changes proposed

Added warning "No Events found" when there are no events.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![Capture](https://github.com/EddieHubCommunity/BioDrop/assets/96465597/19625f40-1066-4779-b3b0-5036e0832462)

## Note to reviewers

2023-09-20 08:13 UTC, accodes21 reviewed
Looks good

2023-09-22 04:57 UTC, eddiejaoude commented on components/user/UserEvents.js
> +      {eventsToShow.length === 0 && manage && (
Now it won't show on the user's profile? This will create another bug

2023-09-22 04:57 UTC, eddiejaoude commented on components/user/UserEvents.js
> +      {eventsToShow.length > 0 && manage && (
This will break on the user's profile

2023-09-22 04:58 UTC, eddiejaoude requested changes
Thank you for your contribution 👍 

The component is used in multiple places, the changes will create bugs in other places it is used

2023-09-22 06:19 UTC, eddiejaoude commented
> Looks good

@accodes21 please do not approve pull requests without reviewing properly, this causes noise and confusing to the contributor and the maintainers

2023-09-28 07:50 UTC, eddiejaoude approved these changes
Thank you 👍

2023-09-28 07:52 UTC, merged