data: d4community
EddieHubCommunity/BioDrop pull request #9176
Opened 2023-09-27 08:38 UTC by D4-Community

As discussed in previous PRs, creating this BioDrop profile for the GitHub Community account.

2023-09-27 08:40 UTC, Dun-sin approved these changes
Looks good to me

2023-09-27 09:05 UTC, sital002 reviewed
Your GitHub username must match your filename instead of ```data/d4community.json```
it should be ```data/D4-Community.json```.
Please make the necessary changes to get your profile merged.

2023-09-27 09:08 UTC, Sagar0-0 commented
D4Community usename is already assigned to our community organization and we can not create a PR from there. So, please allow this username so that we can have consistent url for biodrop as in our other platforms.

2023-09-27 09:32 UTC, eddiejaoude submitted a review, later dismissed
Usernames must match, otherwise various automation won't work - we will have the ability to add additional profiles with a non matching username later

2023-09-27 16:25 UTC, D4-Community commented
Anything else I gotta do?

2023-09-28 09:42 UTC, SaraJaoude commented on data/D4-community.json
> +    },
remove comma:
```suggestion
    }
```

2023-09-28 09:44 UTC, SaraJaoude requested changes
Please make sure your file name matches your GitHub username **exactly** (it is case sensitive). Instead of `data/D4-community.json` it should be`data/D4-Community`. You need to change this for a capital C.

2023-09-29 08:30 UTC, SaraJaoude approved these changes
looks good

2023-09-29 08:31 UTC, merged