data: amit0804-tech
EddieHubCommunity/BioDrop pull request #9269
Opened 2023-10-02 15:13 UTC by amit0804-tech

2023-10-02 16:10 UTC, sital002 commented on amit0804-tech.json
> +    },
```suggestion
    }
```
The comma is not required

2023-10-02 16:11 UTC, kumarsonsoff3 requested changes
Your file should be in data directory. Please rename your file here to `data/amit0804-tech.json`. 

Change the `amit0804-tech.json`  ->  `data/amit0804-tech.json`

Also, make the changes suggested below.

2023-10-02 16:11 UTC, kumarsonsoff3 commented on amit0804-tech.json
> +      "url": "amit0804",
This is an invalid URL. Please update it with your profile URL.

2023-10-02 16:11 UTC, kumarsonsoff3 commented on amit0804-tech.json
> +    },
Also, remove this trailing comma. 

```suggestion
    }
```

2023-10-03 11:45 UTC, kumarsonsoff3 commented
Closing this PR as two new PRs has already been created with the updated changes! #9282, #9284

2023-10-03 11:45 UTC, closed without merging

2023-10-03 11:46 UTC, amit0804-tech commented
Awesome, thanks for the update!

On Tue, Oct 3, 2023, 5:15 PM Priyanshu kumawat ***@***.***>
wrote:

> Closing this PR as two new PRs has already been created with the updated
> changes! #9282 <https://github.com/EddieHubCommunity/BioDrop/pull/9282>,
> #9284 <https://github.com/EddieHubCommunity/BioDrop/pull/9284>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/BioDrop/pull/9269#issuecomment-1744795901>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4LOKQUELYYUWXTIDYWGQVLX5P3F3AVCNFSM6AAAAAA5PST4V2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBUG44TKOJQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>