data: rahulj9a
EddieHubCommunity/BioDrop pull request #9367
Opened 2023-10-05 14:11 UTC by Rahulj9a

## Fixes Issue

 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-10-05 15:14 UTC, Viveksati5143 approved these changes

2023-10-06 09:48 UTC, SaraJaoude commented on data/rahulj9a/testimonials/devfolio.json
> +    "Date":"2023-03-14"
The word `Date` should have a lower case `d`.

Your file name needs to match your GitHub username exactly (it is case sensitive) - you have put lower case `r`.

2023-10-06 09:49 UTC, SaraJaoude requested changes
Your file name needs to match your GitHub username exactly (it is case sensitive) - you have put lower case `r`.

2023-10-06 09:50 UTC, SaraJaoude commented
@Viveksati5143 please do not approve a PR without firstly doing a proper review of it - this causes confusion to the author and maintainers.

2023-10-06 09:54 UTC, SaraJaoude commented
You seem to have added a testimonial about you, on behalf of someone else.  Testimonials are meant to be created by the user who is giving them (in your case, devfolio).  They should also be created via the issue template (rather than manually as you have done) as we have a GitHub Action that will automate the process, so I will close this issue.

2023-10-06 09:54 UTC, closed without merging

2023-10-06 12:04 UTC, Viveksati5143 commented
> @Viveksati5143 please do not approve a PR without firstly doing a proper review of it - this causes confusion to the author and maintainers.

Sorry I thought it is for testing purposes won't approve in future