fixes#9334: adds more information in Step5
EddieHubCommunity/BioDrop pull request #9430
Opened 2023-10-09 16:21 UTC by Vidip-Ghosh

## Fixes Issue

Closes #9334 

## Changes proposed

I've added more information in Open Source Roadmap. 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

<img width="1061" alt="Screenshot 2023-10-09 at 21 44 50" src="https://github.com/EddieHubCommunity/BioDrop/assets/91741581/0225b427-9b76-40cb-84a2-23b217d47392">

## Note to reviewers

2023-10-10 00:38 UTC, amandamartin-dev requested changes
Hello! Thank you for contributing.  In reviewing your changes against the issue, it appears there may be a misunderstanding about the request.  The issue states to add information about code reviews as a way to contribute. 

Take a look and let us know if the issue is clear in what needs to be updated.

2023-10-10 16:25 UTC, Vidip-Ghosh commented
> Hello! Thank you for contributing. In reviewing your changes against the issue, it appears there may be a misunderstanding about the request. The issue states to add information about code reviews as a way to contribute.
> 
> Take a look and let us know if the issue is clear in what needs to be updated.

Its clear, more information related to code review has to be added.

2023-10-10 16:54 UTC, Vidip-Ghosh commented
Code review as a way to contribute can help developers understand the codebase, share feedback that helps them increase their coding skills, catch bugs, ensure no point of failure, increase collaboration among team members, etc.

**Are these points okay or shall I add more?**

2023-10-10 18:56 UTC, amandamartin-dev commented
> Code review as a way to contribute can help developers understand the codebase, share feedback that helps them increase their coding skills, catch bugs, ensure no point of failure, increase collaboration among team members, etc.
> 
> **Are these points okay or shall I add more?**

I think this is almost there - I added one comment inline to consider.

2023-10-11 12:52 UTC, amandamartin-dev submitted a review, later dismissed
This looks good! Thank you for considering the updates.  Another maintainer will confirm as well prior to merging. Thank you for your contributions

2023-10-12 15:12 UTC, SaraJaoude requested changes
Thank you.  However you have added details of how to do code contributions to the Open Source Roadmap Index page. 

The issue refers to adding code contributions to the Step 5 page as a new heading: https://www.biodrop.io/docs/open-source-roadmap/what-to-contribute

Please can you delete the wording you have added from the index page and add this as a new heading in the main body of the Step 5 page.

2023-10-12 15:17 UTC, amandamartin-dev commented
> Thank you. However you have added details of how to do code contributions to the Open Source Roadmap Index page.
> 
> The issue refers to adding code contributions to the Step 5 page as a new heading: https://www.biodrop.io/docs/open-source-roadmap/what-to-contribute
> 
> Please can you delete the wording you have added from the index page and add this as a new heading in the main body of the Step 5 page.

Oh no! This is my fault Sara - I read the issue submitted by Christine and it did not include a link to where these changes should take place. I also thought it meant the index page.  Apologies @Vidip-Ghosh for creating extra work for you

2023-10-14 12:27 UTC, Vidip-Ghosh commented
> > Thank you. However you have added details of how to do code contributions to the Open Source Roadmap Index page.
> > The issue refers to adding code contributions to the Step 5 page as a new heading: https://www.biodrop.io/docs/open-source-roadmap/what-to-contribute
> > Please can you delete the wording you have added from the index page and add this as a new heading in the main body of the Step 5 page.
> 
> Oh no! This is my fault Sara - I read the issue submitted by Christine and it did not include a link to where these changes should take place. I also thought it meant the index page. Apologies @Vidip-Ghosh for creating extra work for you

Can you please review now?

2023-10-17 03:58 UTC, Vidip-Ghosh commented
@amandamartin-dev can you please review the changes? 
Sorry for tagging but due to branch getting updated day by the day, its giving conflicts.

2023-10-17 21:08 UTC, SaraJaoude commented
> amandamartin-dev can you please review the changes? Sorry for tagging but due to branch getting updated day by the day, its giving conflicts.

You are not having conflicts in your branch because no one else is changing this file. You keep merging in main branch into your branch, which is good practice, but this will not cause conflicts - so there is no need to tag a specific maintainer.

Note: Your changes are in the wrong place in the file, I will leave a review with more information.

2023-10-18 01:35 UTC, Vidip-Ghosh commented
> You have added the wording as a new list item under the "Common project improvements" section.
> 
> What we are looking, is for "Code Reviews" to be it's own section on this page (such as "Contributing Guide").

So shall I create a different section?

2023-10-18 11:19 UTC, Vidip-Ghosh commented
<img width="1299" alt="Screenshot 2023-10-18 at 16 48 49" src="https://github.com/EddieHubCommunity/BioDrop/assets/91741581/299d548e-d6ca-42d0-9b11-482d05ee6198">
Like this. Am I right??

2023-10-20 17:58 UTC, Vidip-Ghosh commented
> You have added the wording as a new list item under the "Common project improvements" section.
> 
> What we are looking, is for "Code Reviews" to be it's own section on this page (such as "Contributing Guide").

Please review the changes I've made whether it's correct or not.

2023-10-22 08:07 UTC, Vidip-Ghosh commented
> > You have added the wording as a new list item under the "Common project improvements" section.
> > What we are looking, is for "Code Reviews" to be it's own section on this page (such as "Contributing Guide").
> 
> Please review the changes I've made whether it's correct or not.



> > You have added the wording as a new list item under the "Common project improvements" section.
> > What we are looking, is for "Code Reviews" to be it's own section on this page (such as "Contributing Guide").
> 
> Please review the changes I've made whether it's correct or not.

@SaraJaoude

2023-10-23 09:08 UTC, SaraJaoude commented on pages/docs/open-source-roadmap/what-to-contribute.js
> +          Code Reviews are another way to contribute as it can help developers understand the codebase, share feedback that helps them increase their coding skills, catch bugs, ensure no point of fai
```suggestion
          Code Reviews are another way to contribute as they help understand the codebase, share feedback that improves coding skills, catches bugs and increases collaboration among the community.
```

2023-10-23 09:24 UTC, merged