Added a border in the pricing page for lg+ screens
EddieHubCommunity/BioDrop pull request #9453
Opened 2023-10-11 09:23 UTC by Hero-codes

Edit:
Closes #9337 

## Changes proposed

Added a border in the pricing page for lg+ screens, it enhances the UI.

Before: 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/98174971/4dd06144-d2d2-4409-be03-773f1d829a36)

After:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/98174971/b3578ac3-767d-43dd-9ebc-df4a50a36947)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-10-12 21:34 UTC, waellerbe commented
Excellent example to learn from

2023-10-22 15:53 UTC, akash19coder requested changes

2023-10-22 15:53 UTC, akash19coder commented on pages/pricing.js
> +        onClick: () => { },
Please remove the space in between those curly braces and keep it as it was before.

2023-10-22 15:53 UTC, akash19coder commented on pages/pricing.js
> +                                  "string" ? (
also please remove that extra space that you have added before "string" and make it as it was before

2023-10-22 15:53 UTC, akash19coder commented on pages/pricing.js
> +                      marginLeft: `${(tiers.findIndex((tier) => tier.mostPopular) + 1) * 33
I don't see any changes in these line, however the indentation looks disturbed compared to original state. Please format your document(Ctrl + Shift + I in VS Code) before pushing changes.

2023-10-22 15:58 UTC, akash19coder commented
How does the changes look in light mode? Could you please share the screenshots of light mode as well?

2023-10-24 09:58 UTC, eddiejaoude requested changes
Thank you for your contribution.

Please remove the changes to the lock file, as the package file has not been updated. You can avoid these mistakes by:
- checking the files change and only committing the changes you want
- also using `npm ci` to avoid phantom bugs locally and also generating a new lock file

2023-11-12 09:54 UTC, SaraJaoude commented
As there has been no activity I am closing this issue.

2023-11-12 09:54 UTC, closed without merging