Added hover color for links on open source roadmap
EddieHubCommunity/BioDrop pull request #9503
Opened 2023-10-15 07:08 UTC by HardikChoudhary24

## Fixes Issue #9471

Closes #9471

## Changes proposed

Adding the hover style `  hover:text-tertiary-medium dark:hover:text-tertiary-medium `  to links on open source roadmap for both dark and light mode

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/126149345/2403ae3e-3ac2-4442-8445-ee23440e5e76

## Note to reviewers

NA

2023-10-15 07:12 UTC, AbdullahWins reviewed
Good Job!

2023-10-18 16:36 UTC, HardikChoudhary24 commented
Hey @SaraJaoude I wanted to kindly follow up on my pull request. I understand that you may have a busy schedule, and I appreciate your willingness to review and provide feedback on this contribution.

2023-10-23 09:11 UTC, eddiejaoude commented on pages/docs/open-source-roadmap/index.js
> +                                    className="font-medium text-primary-high dark:text-primary-low  hover:text-tertiary-medium dark:hover:text-tertiary-medium"
I think it would be better to remove the classes and use the `Link` component, this will help us keep consistency within the project for links

2023-10-23 09:11 UTC, eddiejaoude requested changes
Thank you for the contribution, I have left an inline comment

2023-10-23 09:56 UTC, eddiejaoude approved these changes

2023-10-23 10:14 UTC, merged