data:AnikethDeb2004
EddieHubCommunity/BioDrop pull request #9552
Opened 2023-10-21 15:47 UTC by AnikethDeb2004

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-10-21 23:20 UTC, sandramsc requested changes
@AnikethDeb2004 I've left a few comments with some inline suggestions. Also perhaps consider adding some more links, milestones, testimonials to your profile in the future. 

Welcome to the community...


![wlecome2biodrop](https://github.com/EddieHubCommunity/BioDrop/assets/19821445/45a0b9f0-0e85-496f-87d4-62dc755e1017)

2023-10-21 23:20 UTC, sandramsc commented on data/AnikethDeb2004.json
> +  "displayStatsPublic": true,
This tag is no longer required.
```suggestion

```

2023-10-21 23:20 UTC, sandramsc commented on data/AnikethDeb2004.json
> +  "type":"personal",
This tag is no longer required.
```suggestion

```

2023-10-21 23:20 UTC, sandramsc commented on data/AnikethDeb2004.json
> +  "avatar": "https://github.com/AnikethDeb2004.png",
This tag is no longer required.
```suggestion
```

2023-10-22 05:45 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-10-22 05:45 UTC, merged