issue fix #9581: heading strucutre fails WCAG 2.2AA- skipped heading
EddieHubCommunity/BioDrop pull request #9631
Opened 2023-10-26 20:03 UTC by berryjen

## Fixes Issue
closes #9582

## Changes proposed
modified all the <h3> of this page into a <h2>.

modified all the <h3> tags 

## Check List (Check all the applicable boxes) 

- [ X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ X] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.

- [X ] The title of my pull request is a short description of the requested changes.

## Screenshots

 

## Note to reviewers

hopefully the screenshot appears!

2023-10-27 06:13 UTC, sital002 commented on tests/data/_test-profile-user-6.json
> +      "group": "",
Can you explain why are you removing this

2023-10-27 06:16 UTC, sital002 requested changes
The ```package-lock.json``` file shouldn't be changed unless you are installing a new package.
Please revert those changes. Here is the reference video for how to revert ```package-lock.json``` file https://www.youtube.com/watch?v=jHkIXYVpMTo&ab_channel=EddieJaoude

2023-10-27 08:07 UTC, berryjen commented
I had 2 merge conflicts trying to push my commit to my local branch, and VSC wasn't able to merge the conflict on its own so I had to report to doing that in order to push my code changes.

2023-10-27 08:25 UTC, berryjen commented
Is there a way to debug the merge conflict without reinstalling npm? If so, would you be able to help me out? TIA!

2023-10-28 06:22 UTC, eddiejaoude commented
> Is there a way to debug the merge conflict without reinstalling npm? If so, would you be able to help me out? TIA!

You probably had merge conflicts because you are making changes in the `main` branch. You can still remove the changes in the lock file back to the `upstream` (original repo not your fork) as Sital suggested - because you haven't made changes to the `package.json`. To reduce these types of conflicts in the future use any branch other than `main`.

2023-10-28 11:54 UTC, berryjen commented
> > Is there a way to debug the merge conflict without reinstalling npm? If so, would you be able to help me out? TIA!
> 
> You probably had merge conflicts because you are making changes in the `main` branch. You can still remove the changes in the lock file back to the `upstream` (original repo not your fork) as Sital suggested - because you haven't made changes to the `package.json`. To reduce these types of conflicts in the future use any branch other than `main`.

I'm still confused...i was comparing the main branch of my repo to the` main `branch of eddiehub....the local `main` branch on my GH is the branch i was working on....
Do i delete the changes on my `lock json` file, copy& paste the original repo `lock json` file? 
when you mention to use any other branch other than `main`....but there is only 1 branch on my own repo? Or do you mean eddiehub repo? >"<

2023-10-31 12:15 UTC, akash19coder commented
> when you mention to use any other branch other than `main`....but there is only 1 branch on my own repo? Or do you mean eddiehub repo? >
Whenever we are working on an issue, we should create a new branch other than `main` with `git branch <branch-name> command and switch to that branch with `git switch <branch-name>` and make all the changes there related to issue because it prevents the conflicts like we faced earlier with lock-json files

2023-10-31 12:35 UTC, eddiejaoude commented
> I'm still confused...i was comparing the main branch of my repo to the`main`branch of eddiehub....the local `main` branch on my GH is the branch i was working on.... Do i delete the changes on my `lock json` file, copy& paste the original repo `lock json` file? when you mention to use any other branch other than `main`....but there is only 1 branch on my own repo? Or do you mean eddiehub repo? >"<

You can revert the changes to your lock file in a few different ways. I think using the `git checkout` command is probably best here with `git checkout main -- package-lock.json`, I made a video on this https://www.youtube.com/watch?v=jHkIXYVpMTo

On your repo, the `main` branch should not contain any of your changes directly from your commits. After your PR is merged in the original repo (upstream) you sync your main branch (in your fork) with the original repo and then your changes will appear in your `main` branch.

2023-10-31 19:49 UTC, berryjen commented
> `main`

so does that mean in the future, i need to create 2 branches? One is called main, and the other <branch name> , where i will be pushing my commits to? The PR will be raised on <branch name> branch, which then gets merged with the original repo <eddieHub main>? I then synch my <main>  branch with the <eddieHub main>, which means that i'll have the latest version of all the changes made to <eddieHub main>? 
Sorry for the continuous questions, but this Git stuff really is so confusing, esp. in a commercial setting...I do apologize for my lack of knowledge on it. Believe me I've watched YT tutorials, but without actually trying it out, I never know what to do @__@

2023-10-31 20:02 UTC, berryjen commented
> > I'm still confused...i was comparing the main branch of my repo to the`main`branch of eddiehub....the local `main` branch on my GH is the branch i was working on.... Do i delete the changes on my `lock json` file, copy& paste the original repo `lock json` file? when you mention to use any other branch other than `main`....but there is only 1 branch on my own repo? Or do you mean eddiehub repo? >"<
> 
> You can revert the changes to your lock file in a few different ways. I think using the `git checkout` command is probably best here with `git checkout main -- package-lock.json`, I made a video on this https://www.youtube.com/watch?v=jHkIXYVpMTo
> 
> On your repo, the `main` branch should not contain any of your changes directly from your commits. After your PR is merged in the original repo (upstream) you sync your main branch (in your fork) with the original repo and then your changes will appear in your `main` branch.

so does that mean in the future, i need to create 2 branches? One is called main, and the other <branch name> , where i will be pushing my commits to? The PR will be raised on <branch name> branch, which then gets merged with the original repo <eddieHub main>? I then synch my <main>  branch with the <eddieHub main>, which means that i'll have the latest version of all the changes made to <eddieHub main>? Is this mental model correct?
Sorry for the continuous questions, but this Git stuff really is so confusing, esp. in a commercial setting...I do apologize for my lack of knowledge on it. Believe me I've watched YT tutorials, but without actually trying it out, my mental schema in my head is always different from reality

2023-10-31 20:08 UTC, eddiejaoude commented
It is confusing, you are right the best way to understand is to try it. `main` will be created on your fork repo already, you should always keep this up to date with the original repo and then create your branches from there

2023-10-31 23:29 UTC, berryjen commented
additionally, i did `git status`, which displays theres nothing to commit....im unsure if the reverted changes has been committed to my local branch?!
![Screenshot 2023-10-31 at 11 27 26 PM](https://github.com/EddieHubCommunity/BioDrop/assets/73888356/b7c074e2-f766-4a24-a1ae-9927b7d33592)

2023-11-02 07:58 UTC, eddiejaoude commented
> additionally, i did git status, which displays theres nothing to commit....im unsure if the reverted changes has been committed to my local branch?!

sorry, it won't work because you made changes in the main branch. Let me try to think of another way

2023-11-02 21:43 UTC, berryjen commented
Ahh ok..looks like i made a big oppose 🥲

2023-11-02 23:25 UTC, eddiejaoude commented
I can try to fix via a temporary branch - I will take a look tomorrow

2023-11-03 03:06 UTC, Abhishek-90 commented
> [Screenshot 2023-10-31 at 8 16 07 PM](https://github.com/EddieHubCommunity/BioDrop/assets/73888356/f0b00f3b-c757-464b-bf15-22e3352dc5ad) Nothing appeared on the terminal...is this correct?!

I would say to use `git bash` rather than VSC's inbuilt terminal for git related operations. It will give you a clear picture.

2023-11-03 10:41 UTC, merged

2023-11-03 10:44 UTC, eddiejaoude commented
I fixed the lock file changes in a temporary PR here https://github.com/EddieHubCommunity/BioDrop/pull/9719

2023-11-08 11:36 UTC, berryjen commented
@eddiejaoude sorry for the late reply, just finished midterms as of yesterday, so spent all last week and early this week studying...@__@ the solution was that you moved #9581 onto a separate branch and then merged the `new` branch onto `eddiehub main`?