data: VidipGhosh
EddieHubCommunity/BioDrop pull request #9643
Opened 2023-10-27 17:42 UTC by Vidip-Ghosh

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-10-27 17:56 UTC, sital002 requested changes
Your filename must match your github username instead of ```data/VidipGhosh.json``` it should be ```data/Vidip-Ghosh.json```.
Please make the necessary changes to get your profile merged.

2023-10-27 17:57 UTC, sital002 commented on data/VidipGhosh.json
> +  "tags": ["travelling","photography","exploring new technologies"]
```suggestion
  "tags": ["travelling","photography","exploring new technologies"],
```
There is a comma missing here

2023-10-28 06:35 UTC, Vidip-Ghosh commented
I've made the necessary changes. Please review.

2023-10-28 06:37 UTC, sital002 approved these changes
Looks good 👍
Welcome to Eddiehub community 🎉🎉

2023-10-28 06:37 UTC, merged