Create aungkohtat.json
EddieHubCommunity/BioDrop pull request #9688
Opened 2023-10-30 16:18 UTC by aungkohtat

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-10-30 16:57 UTC, sital002 requested changes
Please put the file inside data folder instead of ```aungkohtat.json``` it should be ```data/aungkohtat.json```.
Please make the necessary changes to get your profile merged.

2023-10-31 09:12 UTC, SaraJaoude requested changes
You now have two files.  Please check the "Files Changed" tab - the file called `aungkohtat.json` needs to be deleted.

2023-10-31 09:12 UTC, SaraJaoude commented on data/aungkohtat.json
> +    {
add comma:
```suggestion
    },
    {
```

2023-11-12 18:50 UTC, sital002 reviewed
Since there has been no activity for 2 weeks I am closing this PR.
You can always open new PR with the lastest changes.

2023-11-12 18:50 UTC, closed without merging