move premium check to middleware
EddieHubCommunity/BioDrop pull request #9743
Opened 2023-11-07 19:18 UTC by dmitrykulakovfrontend

## Fixes Issue
Closes #9630

## Changes proposed
Update JWT, refactor middleware.js, remove premium checks in getServerSideProps and move them to middleware.js

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-11-08 22:28 UTC, eddiejaoude commented on middleware.js
> -  }
I think this is still required?

2023-11-08 22:29 UTC, eddiejaoude requested changes
Thank you 👍 

Looks good, I left an inline question. 

Please can you also resolve conflicts

2023-11-15 09:49 UTC, eddiejaoude commented
Thank you for making the changes. Could you check your Prettier settings, it looks like extra lines are being reformatted, which makes it more difficult to review "actual" changes

2023-11-22 06:13 UTC, dmitrykulakovfrontend commented
I'm apologizing for the issue with prettier, it should be fixed now

2023-11-28 07:56 UTC, eddiejaoude commented
> I'm apologizing for the issue with prettier, it should be fixed now

thank you 👍  sorry for my slow reply, I will be looking at this PR next

2023-12-08 05:19 UTC, eddiejaoude commented
I can fix the conflicts, as it has conflicted with my changes

2024-06-08 11:05 UTC, eddiejaoude approved these changes
Thank you 👍 

note: I resolved the conflicts

2024-06-08 11:05 UTC, merged