data: shaik.mb666.json
EddieHubCommunity/BioDrop pull request #9790
Opened 2023-11-14 13:36 UTC by mansoor666

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-11-14 14:26 UTC, sital002 commented on data/shaik.mb666.json
> +    },
```suggestion
    }
```
the trailing comma is not required

2023-11-14 14:28 UTC, sital002 requested changes
Your GitHub username must match your filename instead of ```data/shaik.mb666.json``` it should be ```data/mansoor666.json```
Please make the necessary changes to get your profile merged.

2023-11-16 13:43 UTC, mansoor666 commented
Updated file name

2023-11-16 13:46 UTC, mansoor666 commented
updated file name as required

2023-11-16 13:46 UTC, mansoor666 commented
updated file name as required.

2023-11-17 07:45 UTC, mansoor666 commented
m

2023-11-17 16:45 UTC, accodes21 reviewed
Ig you have already created your profile using form here: biodrop.io/mansoor666, you can close this PR as it will be obsolete

2023-11-19 11:28 UTC, SaraJaoude commented
> Ig you have already created your profile using form here: biodrop.io/mansoor666, you can close this PR as it will be obsolete

I am closing this PR for the above reason.  

If you are looking to edit your existing Profile then you may want to check out our Editing Guide in [Docs.](https://www.biodrop.io/docs)

2023-11-19 11:28 UTC, closed without merging