Create Mazeedkmk204.json
EddieHubCommunity/BioDrop pull request #9792
Opened 2023-11-17 07:43 UTC by Mazeedkmk204

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-11-17 13:44 UTC, amandamartin-dev requested changes

2023-11-17 13:44 UTC, amandamartin-dev commented on data/Mazeedkmk204.json
> +      "name": "jabeen taj automobiles",
You forgot to add your URL here... like this `"url": "http://examplelink.io",`

2023-11-17 13:44 UTC, amandamartin-dev commented on data/Mazeedkmk204.json
> +      "name": "jabeen taj automobiles",
link to the docs if you need them [Profile with JSON](https://www.biodrop.io/docs/quickstart-json)

2023-11-17 16:06 UTC, sital002 reviewed
It looks like you already have created a biodrop profile using forms there is no point in creating it with json again since it will be ignored here is your biodrop profile  using forms https://www.biodrop.io/Mazeedkmk204.
You can close this Pull Request.

2023-11-19 11:30 UTC, SaraJaoude commented
> It looks like you already have created a biodrop profile using forms there is no point in creating it with json again since it will be ignored here is your biodrop profile using forms https://www.biodrop.io/Mazeedkmk204. You can close this Pull Request.

Closing this PR for the reasons mentioned above. If you wish to edit your Profile then please check out the[ Docs for Editing through Forms.](https://www.biodrop.io/docs/how-to-guides/editing-forms)

2023-11-19 11:30 UTC, closed without merging