Issue (No Space between add link and first link #9406 ) is Fixed.
EddieHubCommunity/BioDrop pull request #9822
Opened 2023-11-22 19:40 UTC by donishyar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot 2023-11-22 235514](https://github.com/EddieHubCommunity/BioDrop/assets/35393325/81b00b8e-4577-42d8-aaeb-1ccd619042fe)

## Note to reviewers

2023-11-23 03:12 UTC, sital002 commented
Issue link https://github.com/EddieHubCommunity/BioDrop/issues/9406

2023-11-23 14:43 UTC, akash19coder commented
@donishyar looks good👌

2023-11-23 19:21 UTC, eddiejaoude commented on components/account/manage/Edit.js
> +        className="rounded-full bg-secondary-medium p-2 text-white shadow-sm hover:bg-tertiary-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outlin
how do these changes effect other places that use the `Edit` component?

2023-11-23 19:21 UTC, eddiejaoude commented on components/user/UserLink.js
> +    <div className="flex flex-row gap-8 w-full pl-4">
How does this effect the profile page?

2023-11-25 04:43 UTC, eddiejaoude requested changes
This is a global change, how does this affect **all** other pages?

2023-11-25 06:48 UTC, donishyar commented
> This is a global change, how does this affect **all** other pages?

> yes, it will affect all pages that uses page layout.

2023-11-25 10:47 UTC, eddiejaoude commented
Yes, that is my point, did you test all other pages to make sure they still work after this change?

2023-11-26 16:37 UTC, donishyar commented
> Yes, that is my point, did you test all other pages to make sure they still work after this change?

> Yeah , i checked it and i have'nt encounter  any issue.

2023-11-26 16:37 UTC, closed without merging

2023-11-26 18:19 UTC, eddiejaoude commented
@donishyar did you mean to close the PR?