data: shaileshthakur1
EddieHubCommunity/BioDrop pull request #9832
Opened 2023-11-25 08:08 UTC by shaileshthakur1

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-11-25 11:56 UTC, sital002 commented on data/shaileshthakur1.json
> +  "displayStatsPublic": true,
```suggestion
```
  ```displayStatsPublic``` is not required.

2023-11-25 11:58 UTC, sital002 commented on data/shaileshthakur1.json
> +  "type": "personal",
```suggestion
```
```type``` isnot required

2023-11-25 11:59 UTC, sital002 commented on data/shaileshthakur1.json
> +  "avatar": "https://github.com/shaileshthakur1.png"
```suggestion
  "avatar": "https://github.com/shaileshthakur1.png"
```
```avatar``` property isnot required

2023-11-25 12:01 UTC, sital002 requested changes
Please make the necessary changes to get your profile merged.

2023-11-26 09:03 UTC, shaileshthakur1 commented
hey @sital002 , I've updated it all. Please review now.

2023-11-26 10:12 UTC, sital002 approved these changes
Looks good 👍

2023-11-26 10:12 UTC, merged