Create fahmedo -profile.json
EddieHubCommunity/BioDrop pull request #9973
Opened 2023-12-20 10:22 UTC by Fahmedo

Create a json file and add my profiles details

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-12-20 11:22 UTC, Sindhuinti requested changes
Please add comma as suggested

2023-12-20 11:22 UTC, Sindhuinti commented on data/fahmedo -profile.json
> +    }
```suggestion
    },
```

2023-12-20 11:22 UTC, Sindhuinti commented on data/fahmedo -profile.json
> +    }
```suggestion
    },
```

2023-12-20 11:22 UTC, Sindhuinti commented on data/fahmedo -profile.json
> +    }
```suggestion
    },
```

2023-12-20 13:46 UTC, SaraJaoude submitted a review, later dismissed
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/fahmedo -profile.json`   it should be `data/Fahmedo.json`

I would suggest you look at our QuickStart Guide  with JSON (especially section 7) in Docs: https://www.biodrop.io/docs/quickstart-json to help you update this Pull Request.

2023-12-21 09:47 UTC, SaraJaoude approved these changes
Thank you for making the changes, I can now merge this PR.

2023-12-21 09:47 UTC, merged