data: Glenn444
EddieHubCommunity/BioDrop pull request #9983
Opened 2023-12-20 14:35 UTC by Glenn444

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-12-21 05:42 UTC, kumarsonsoff3 requested changes
Please add the file extension `.json` in the end your filename. Rename your file [here](https://github.com/Glenn444/BioDrop/edit/main/data/Glenn444) to `data/Glenn444.json`. 

Change `Glenn444`  ->  `Glenn444.json`

Also, make the below suggested changes.

2023-12-21 05:42 UTC, kumarsonsoff3 commented on data/Glenn444
> +  "bio": "Open Source contributor | Software engineer"
Please add the missing comma here. 

```suggestion
  "bio": "Open Source contributor | Software engineer",
```

2023-12-21 05:42 UTC, kumarsonsoff3 commented on data/Glenn444
> +    },
Also remove this trailing comma here. 

```suggestion
    }
```

2024-01-06 09:03 UTC, SaraJaoude commented
We look forward to seeing your Profile on BioDrop, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at t[hese Docs](https://www.biodrop.io/docs/quickstart-json) which will help with the suggested changes the maintainers have proposed. 

Please remember you can also create your Profile using [Forms](https://www.biodrop.io/docs/quickstart-forms).

2024-01-06 09:03 UTC, closed without merging